#!/usr/bin/env python3

'''
TODO:
	- publish
	- manage
	- usage for individual commands
'''
import os
import sys
import shutil
import re
import datetime

class ParseException(Exception):
	pass

# Recursively cd up until either _config.yml is found or we reach /
def getWebsiteRoot():
	path = str(os.getcwd())
	while path != "/":
		if os.path.isfile("./_config.yml") and not os.path.islink("./_config.yml"):
			return path
		else:
			os.chdir("..")
			path = str(os.getcwd())
	raise Exception()

# Asks a y/n question, returns true if y, false if n
def askYN(question):
	print("[draught] " + question, end=" (Y/n) ")
	answer = input().lower()
	
	if answer == "" or answer == "y" or answer == "yes":
		return True
	else:
		return False

# Ensure that a directory exists, return false if it does not
def ensureDir(path):
	fullPath = os.path.join(siteRoot, path)
	if not os.path.exists(fullPath):
		if askYN("Directory " + path + " has not been found, would you like to create it?"):
			try:
				os.mkdir(fullPath)
				return True
			except:
				return False
		else:
			return False
	else:
		return True

# Condition strings for URLs
def slugify(string, date=False):
	slug = string.lower()
	slug = re.sub("[^(a-z0-9)]+", "-", slug).strip("-")
	if date:
		today = datetime.date.today()
		slug = str(today.year) + "-" + str(today.month) + "-" + str(today.day) + "-" + slug
	return slug
	
# Show top-level help info
def showDraughtHelp():
	print("usage: draught <command> [<args>]\n")
	print("Available commands:")
	print("\tnew\tcreate new content")
	print("\tpublish\tmake drafts available\n")
	print("See 'draught help <command>' for information about commands.")

# Create a new post
def createNewPost(title, extension="md"):
	if ensureDir("_posts"):
		fileName = slugify(title, date=True) + "." + extension
		postPath = os.path.join(siteRoot, "_posts", fileName)
		if not os.path.exists(postPath):
			open(postPath, 'a').close()
		else:
			print("[draught] Error:", fileName, "already exists")
	else:
		print("[draught] Error: _posts/ does not exist, or requires higher privileges")

# Create a new draft
def createNewDraft(title, extension="md"):
	if ensureDir("_drafts"):
		fileName = slugify(title) + "." + extension
		draftPath = os.path.join(siteRoot, "_drafts", fileName)
		if not os.path.exists(draftPath):
			open(draftPath, 'a').close()
		else:
			print("[draught] Error:", fileName, "already exists")
	else:
		print("[draught] Error: _drafts/ does not exist, or requires higher privileges")

# The entry point
if __name__ == "__main__":

	# first off, check if cwd is in a jekyll directory
	try:
		siteRoot = getWebsiteRoot()
	except:
		print("[draught] Error: this is not a Jekyll website")
		sys.exit()
	try:
		if sys.argv[1] == "new":
			if sys.argv[2] == "post":
				createNewPost(sys.argv[3])
			elif sys.argv[2] == "draft":
				createNewDraft(sys.argv[3])
			else:
				raise ParseException(sys.argv[2])
		elif sys.argv[1] == "publish":
			print("publish")
		else:
			raise ParseException(sys.argv[1])
	except ParseException as pe:
		print("[draught] Error: unknown command:", pe.args[0])
		showDraughtHelp()
	except IndexError as ie:
		print("[draught] Error: arguments missing")
		showDraughtHelp()
	
